# GraphQL configuration for gqlgen
schema:
  - graph/schema/*.graphqls

exec:
  filename: graph/generated/generated.go
  package: generated

model:
  filename: graph/model/models_gen.go
  package: model

resolver:
  layout: follow-schema
  dir: graph
  package: graph
  filename_template: "{name}.resolvers.go"

autobind:
  - "archie-core-shopify-layer/graph/model"

models:
  Time:
    model:
      - archie-core-shopify-layer/graph/scalars.Time
