package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"archie-core-shopify-layer/graph/generated"
	"archie-core-shopify-layer/graph/model"
	"archie-core-shopify-layer/graph/scalars"
	"context"
	"fmt"
	"time"
)

// ShopifyInstallApp is the resolver for the shopify_installApp field.
func (r *mutationResolver) ShopifyInstallApp(ctx context.Context, input model.InstallAppInput) (*model.InstallAppPayload, error) {
	authURL, err := r.shopifyService.GenerateAuthURL(ctx, input.Shop, input.Scopes)
	if err != nil {
		return nil, err
	}

	return &model.InstallAppPayload{
		AuthURL: authURL,
	}, nil
}

// ShopifyExchangeToken is the resolver for the shopify_exchangeToken field.
func (r *mutationResolver) ShopifyExchangeToken(ctx context.Context, input model.ExchangeTokenInput) (*model.ExchangeTokenPayload, error) {
	shop, err := r.shopifyService.ExchangeToken(ctx, input.Shop, input.Code)
	if err != nil {
		return nil, err
	}

	return &model.ExchangeTokenPayload{
		Shop: &model.Shop{
			ID:        shop.ID,
			Domain:    shop.Domain,
			Scopes:    shop.Scopes,
			CreatedAt: scalars.Time(shop.CreatedAt),
			UpdatedAt: scalars.Time(shop.UpdatedAt),
		},
		AccessToken: shop.AccessToken,
	}, nil
}

// ShopifyShop is the resolver for the shopify_shop field.
func (r *queryResolver) ShopifyShop(ctx context.Context, domain string) (*model.Shop, error) {
	shop, err := r.shopifyService.GetShop(ctx, domain)
	if err != nil {
		return nil, err
	}

	if shop == nil {
		return nil, nil
	}

	return &model.Shop{
		ID:        shop.ID,
		Domain:    shop.Domain,
		Scopes:    shop.Scopes,
		CreatedAt: scalars.Time(shop.CreatedAt),
		UpdatedAt: scalars.Time(shop.UpdatedAt),
	}, nil
}

// ShopifyProducts is the resolver for the shopify_products field.
func (r *queryResolver) ShopifyProducts(ctx context.Context, domain string) ([]*model.Product, error) {
	products, err := r.shopifyService.GetProducts(ctx, domain)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Product, len(products))
	for i, p := range products {
		createdAt, _ := time.Parse(time.RFC3339, p.CreatedAt.String())
		updatedAt, _ := time.Parse(time.RFC3339, p.UpdatedAt.String())

		result[i] = &model.Product{
			ID:          fmt.Sprintf("%d", p.Id),
			Title:       p.Title,
			Handle:      &p.Handle,
			Vendor:      &p.Vendor,
			ProductType: &p.ProductType,
			CreatedAt:   scalars.Time(createdAt),
			UpdatedAt:   scalars.Time(updatedAt),
		}
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
