// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"archie-core-shopify-layer/graph/scalars"
)

type ExchangeTokenInput struct {
	Shop string `json:"shop"`
	Code string `json:"code"`
}

type ExchangeTokenPayload struct {
	Shop        *Shop  `json:"shop"`
	AccessToken string `json:"accessToken"`
}

type InstallAppInput struct {
	Shop   string   `json:"shop"`
	Scopes []string `json:"scopes"`
}

type InstallAppPayload struct {
	AuthURL string `json:"authUrl"`
}

type Mutation struct {
}

type Product struct {
	ID          string       `json:"id"`
	Title       string       `json:"title"`
	Handle      *string      `json:"handle,omitempty"`
	Vendor      *string      `json:"vendor,omitempty"`
	ProductType *string      `json:"productType,omitempty"`
	CreatedAt   scalars.Time `json:"createdAt"`
	UpdatedAt   scalars.Time `json:"updatedAt"`
}

type Query struct {
}

type Shop struct {
	ID        string       `json:"id"`
	Domain    string       `json:"domain"`
	Scopes    []string     `json:"scopes"`
	CreatedAt scalars.Time `json:"createdAt"`
	UpdatedAt scalars.Time `json:"updatedAt"`
}

type WebhookEvent struct {
	ID        string       `json:"id"`
	Topic     string       `json:"topic"`
	Shop      string       `json:"shop"`
	Verified  bool         `json:"verified"`
	CreatedAt scalars.Time `json:"createdAt"`
}
